oa3_spec: app/src/main/resources/swagger/api-docs.json
name: opex_api-ms-party-registry-proxy
location: West Europe
timespan: 30m # Default, a number or a timespan https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/timespan
evaluation_frequency: 10
evaluation_time_window: 30
event_occurrences: 4 # After 5*4=20 min
data_source: /subscriptions/813119d7-0943-46ed-8ebe-cebe24f9106c/resourceGroups/selc-p-vnet-rg/providers/Microsoft.Network/applicationGateways/selc-p-app-gw
action_groups:
  - /subscriptions/813119d7-0943-46ed-8ebe-cebe24f9106c/resourceGroups/selc-p-monitor-rg/providers/microsoft.insights/actionGroups/PagoPA
  - /subscriptions/813119d7-0943-46ed-8ebe-cebe24f9106c/resourceGroups/selc-p-monitor-rg/providers/microsoft.insights/actionGroups/SlackPagoPA
overrides:
  hosts: # Use these hosts instead of those inside the OpenApi spec
    - api.selfcare.pagopa.it
  endpoints:
    /aoo:
      response_time_threshold: 100 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default:
      availability_threshold: 0.8
      availability_evaluation_frequency: 10 # Default: 10
      availability_evaluation_time_window: 30 # Default: 20
      availability_event_occurrences: 3 # Default: 1
    /aoo/{codiceUniAoo}:
      response_time_threshold: 100 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default:
      availability_threshold: 0.8
      availability_evaluation_frequency: 10 # Default: 10
      availability_evaluation_time_window: 30 # Default: 20
      availability_event_occurrences: 3 # Default: 1
    /categories:
      response_time_threshold: 100 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default:
      availability_threshold: 0.8
      availability_evaluation_frequency: 10 # Default: 10
      availability_evaluation_time_window: 30 # Default: 20
      availability_event_occurrences: 3 # Default: 1
    /geotaxonomies:
      response_time_threshold: 100 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default:
      availability_threshold: 0.8
      availability_evaluation_frequency: 10 # Default: 10
      availability_evaluation_time_window: 30 # Default: 20
      availability_event_occurrences: 3 # Default: 1
    /geotaxonomies/{geotaxId}:
      response_time_threshold: 100 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default:
      availability_evaluation_frequency: 10 # Default: 10
      availability_evaluation_time_window: 30 # Default: 20
      availability_event_occurrences: 3 # Default: 1
      availability_threshold: 0.8
    /info-camere/institutions:
      response_time_threshold: 100 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default:
      availability_threshold: 0.8
      availability_evaluation_frequency: 10 # Default: 10
      availability_evaluation_time_window: 30 # Default: 20
      availability_event_occurrences: 3 # Default: 1
    /infocamere-pdnd/institution/{taxCode}:
      response_time_threshold: 100 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default:
      availability_threshold: 0.8
      availability_evaluation_frequency: 10 # Default: 10
      availability_evaluation_time_window: 30 # Default: 20
      availability_event_occurrences: 3 # Default: 1
    /institutions:
      response_time_threshold: 100 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default:
      availability_threshold: 0.8
      availability_evaluation_frequency: 10 # Default: 10
      availability_evaluation_time_window: 30 # Default: 20
      availability_event_occurrences: 3 # Default: 1
    /institutions/{id}:
      response_time_threshold: 100 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default:
      availability_threshold: 0.8
      availability_evaluation_frequency: 10 # Default: 10
      availability_evaluation_time_window: 30 # Default: 20
      availability_event_occurrences: 3 # Default: 1
    /insurance-companies:
      response_time_threshold: 100 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default:
      availability_threshold: 0.8
      availability_evaluation_frequency: 10 # Default: 10
      availability_evaluation_time_window: 30 # Default: 20
      availability_event_occurrences: 3 # Default: 1
    /insurance-companies/{taxId}:
      response_time_threshold: 100 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default:
      availability_threshold: 0.8
      availability_evaluation_frequency: 10 # Default: 10
      availability_evaluation_time_window: 30 # Default: 20
      availability_event_occurrences: 3 # Default: 1
    /insurance-companies/origin/{originId}:
      response_time_threshold: 100 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default:
      availability_threshold: 0.8
      availability_evaluation_frequency: 10 # Default: 10
      availability_evaluation_time_window: 30 # Default: 20
      availability_event_occurrences: 3 # Default: 1
    /national-registries/legal-address:
      response_time_threshold: 100 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default:
      availability_threshold: 0.8
      availability_evaluation_frequency: 10 # Default: 10
      availability_evaluation_time_window: 30 # Default: 20
      availability_event_occurrences: 3 # Default: 1
    /national-registries/verify-legal:
      response_time_threshold: 100 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default:
      availability_threshold: 0.8
      availability_evaluation_frequency: 10 # Default: 10
      availability_evaluation_time_window: 30 # Default: 20
      availability_event_occurrences: 3 # Default: 1
    /origins/{origin}/categories/{code}:
      response_time_threshold: 100 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default:
      availability_threshold: 0.8
      availability_evaluation_frequency: 10 # Default: 10
      availability_evaluation_time_window: 30 # Default: 20
      availability_event_occurrences: 3 # Default: 1
    /stations:
      response_time_threshold: 100 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default:
      availability_threshold: 0.8
      availability_evaluation_frequency: 10 # Default: 10
      availability_evaluation_time_window: 30 # Default: 20
      availability_event_occurrences: 3 # Default: 1
    /stations/{taxId}:
      response_time_threshold: 100 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default:
      availability_threshold: 0.8
      availability_evaluation_frequency: 10 # Default: 10
      availability_evaluation_time_window: 30 # Default: 20
      availability_event_occurrences: 3 # Default: 1
    /uo:
      response_time_threshold: 100 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default:
      availability_threshold: 0.8
      availability_evaluation_frequency: 10 # Default: 10
      availability_evaluation_time_window: 30 # Default: 20
      availability_event_occurrences: 3 # Default: 1
    /uo/{codiceUniUo}:
      response_time_threshold: 100 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default:
      availability_threshold: 0.8
      availability_evaluation_frequency: 10 # Default: 10
      availability_evaluation_time_window: 30 # Default: 20
      availability_event_occurrences: 3 # Default: 1